"""init

Revision ID: 5c70d59b4897
Revises: 
Create Date: 2020-05-10 03:45:25.429494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c70d59b4897'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chrome_url', sa.String(), nullable=True),
    sa.Column('firefox_url', sa.String(), nullable=True),
    sa.Column('safari_url', sa.String(), nullable=True),
    sa.Column('opera_url', sa.String(), nullable=True),
    sa.Column('edge_url', sa.String(), nullable=True),
    sa.Column('fallback_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    # ### end Alembic commands ###
