"""reinit

Revision ID: 78002a417c2c
Revises: 5c70d59b4897
Create Date: 2022-04-13 21:15:58.989835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78002a417c2c'
down_revision = '5c70d59b4897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chrome_url', sa.String(), nullable=True),
    sa.Column('firefox_url', sa.String(), nullable=True),
    sa.Column('safari_url', sa.String(), nullable=True),
    sa.Column('opera_url', sa.String(), nullable=True),
    sa.Column('edge_url', sa.String(), nullable=True),
    sa.Column('fallback_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('links')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('chrome_url', sa.VARCHAR(), nullable=True),
    sa.Column('firefox_url', sa.VARCHAR(), nullable=True),
    sa.Column('safari_url', sa.VARCHAR(), nullable=True),
    sa.Column('opera_url', sa.VARCHAR(), nullable=True),
    sa.Column('edge_url', sa.VARCHAR(), nullable=True),
    sa.Column('fallback_url', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('link')
    # ### end Alembic commands ###
